### ISSUE TITLE
File upload and login redirect not working after updating to latest sdk

### ISSUE THREAD

**Issue by chriscom78** [lohanidamodar/flutter_appwrite_starter#7]
On login i am getting [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type 'bool' is not a subtype of type 'int'

If I refresh the app, I am taken to the splash screen and then redirected to the main page.

Then if I try to change the profile image I am getting an error too...
E/flutter (11506): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type 'MultipartFile' is not a subtype of type 'InputFile'
E/flutter (11506): #0      ApiService.uploadFile
package:myapp/…/service/api_service.dart:51
E/flutter (11506): #1      EditProfileState.uploadImage
package:myapp/…/pages/edit_profile.dart:221
E/flutter (11506): #2      EditProfileState.build.<anonymous closure>

**Comment by lohanidamodar** [comment]
I'm yet to update this to Support the stable version of Appwrite. Which I'll do soon.

**Comment by lohanidamodar** [comment]
It's updated to latest Appwrite support.
